using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Vegetables : MonoBehaviour
{
    public List<Word> words;
    public Vegetables()
    {
        words = new List<Word>
        {
            new Word { id =  1,callNumber = 0,numberOfLetters =3,word = "Лук",  description = ""},
new Word { id =  2,callNumber = 0,numberOfLetters =3,word = "Ямс",  description = ""},
new Word { id =  3,callNumber = 0,numberOfLetters =3,word = "Нут",  description = ""},
new Word { id =  4,callNumber = 0,numberOfLetters =4,word = "Бобы",  description = ""},
new Word { id =  5,callNumber = 0,numberOfLetters =4,word = "Лоба",  description = ""},
new Word { id =  6,callNumber = 0,numberOfLetters =4,word = "Мака",  description = ""},
new Word { id =  7,callNumber = 0,numberOfLetters =4,word = "Репа",  description = ""},
new Word { id =  8,callNumber = 0,numberOfLetters =4,word = "Хрен",  description = ""},
new Word { id =  9,callNumber = 0,numberOfLetters =4,word = "Чили",  description = ""},
new Word { id =  10  ,callNumber = 0,numberOfLetters =4,word = "Чуфа",  description = ""},
new Word { id =  11  ,callNumber = 0,numberOfLetters =4,word = "Якон",  description = ""},
new Word { id =  12  ,callNumber = 0,numberOfLetters =5,word = "Бамия",  description = ""},
new Word { id =  13  ,callNumber = 0,numberOfLetters =5,word = "Бамия",  description = ""},
new Word { id =  14  ,callNumber = 0,numberOfLetters =5,word = "Батат",  description = ""},
new Word { id =  15  ,callNumber = 0,numberOfLetters =5,word = "Буряк",  description = ""},
new Word { id =  16  ,callNumber = 0,numberOfLetters =5,word = "Горох",  description = ""},
new Word { id =  17  ,callNumber = 0,numberOfLetters =5,word = "Латук",  description = ""},
new Word { id =  18  ,callNumber = 0,numberOfLetters =5,word = "Люффа",  description = ""},
new Word { id =  19  ,callNumber = 0,numberOfLetters =5,word = "Перец",  description = ""},
new Word { id =  20  ,callNumber = 0,numberOfLetters =5,word = "Редис",  description = ""},
new Word { id =  21  ,callNumber = 0,numberOfLetters =5,word = "Салат",  description = ""},
new Word { id =  22  ,callNumber = 0,numberOfLetters =5,word = "Тыква",  description = ""},
new Word { id =  23  ,callNumber = 0,numberOfLetters =5,word = "Укроп",  description = ""},
new Word { id =  24  ,callNumber = 0,numberOfLetters =5,word = "Чабер",  description = ""},
new Word { id =  25  ,callNumber = 0,numberOfLetters =5,word = "Чайот",  description = ""},
new Word { id =  26  ,callNumber = 0,numberOfLetters =5,word = "Томат",  description = ""},
new Word { id =  27  ,callNumber = 0,numberOfLetters =5,word = "Черри",  description = ""},
new Word { id =  28  ,callNumber = 0,numberOfLetters =6,word = "Брюква",  description = ""},
new Word { id =  29  ,callNumber = 0,numberOfLetters =6,word = "Дайкон",  description = ""},
new Word { id =  30  ,callNumber = 0,numberOfLetters =6,word = "Жеруха",  description = ""},
new Word { id =  31  ,callNumber = 0,numberOfLetters =6,word = "Зелень",  description = ""},
new Word { id =  32  ,callNumber = 0,numberOfLetters =6,word = "Ипомея",  description = ""},
new Word { id =  33  ,callNumber = 0,numberOfLetters =6,word = "Катран",  description = ""},
new Word { id =  34  ,callNumber = 0,numberOfLetters =6,word = "Кивано",  description = ""},
new Word { id =  35  ,callNumber = 0,numberOfLetters =6,word = "Огурец",  description = ""},
new Word { id =  36  ,callNumber = 0,numberOfLetters =6,word = "Ревень",  description = ""},
new Word { id =  37  ,callNumber = 0,numberOfLetters =6,word = "Редька",  description = ""},
new Word { id =  38  ,callNumber = 0,numberOfLetters =6,word = "Сараха",  description = ""},
new Word { id =  39  ,callNumber = 0,numberOfLetters =6,word = "Свекла",  description = ""},
new Word { id =  40  ,callNumber = 0,numberOfLetters =6,word = "Спаржа",  description = ""},
new Word { id =  41  ,callNumber = 0,numberOfLetters =6,word = "Уллюко",  description = ""},
new Word { id =  42  ,callNumber = 0,numberOfLetters =6,word = "Фасоль",  description = ""},
new Word { id =  43  ,callNumber = 0,numberOfLetters =6,word = "Хикама",  description = ""},
new Word { id =  44  ,callNumber = 0,numberOfLetters =6,word = "Чеснок",  description = ""},
new Word { id =  45  ,callNumber = 0,numberOfLetters =6,word = "Чистец",  description = ""},
new Word { id =  46  ,callNumber = 0,numberOfLetters =6,word = "Шпинат",  description = ""},
new Word { id =  47  ,callNumber = 0,numberOfLetters =6,word = "Щавель",  description = ""},
new Word { id =  48  ,callNumber = 0,numberOfLetters =7,word = "Авокадо",  description = ""},
new Word { id =  49  ,callNumber = 0,numberOfLetters =7,word = "Ангурия",  description = ""},
new Word { id =  50  ,callNumber = 0,numberOfLetters =7,word = "Аррорут",  description = ""},
new Word { id =  51  ,callNumber = 0,numberOfLetters =7,word = "Артишок",  description = ""},
new Word { id =  52  ,callNumber = 0,numberOfLetters =7,word = "Базелла",  description = ""},
new Word { id =  53  ,callNumber = 0,numberOfLetters =7,word = "Базилик",  description = ""},
new Word { id =  54  ,callNumber = 0,numberOfLetters =7,word = "Горчица",  description = ""},
new Word { id =  55  ,callNumber = 0,numberOfLetters =7,word = "Кабачок",  description = ""},
new Word { id =  56  ,callNumber = 0,numberOfLetters =7,word = "Каперсы",  description = ""},
new Word { id =  57  ,callNumber = 0,numberOfLetters =7,word = "Капуста",  description = ""},
new Word { id =  58  ,callNumber = 0,numberOfLetters =7,word = "Кислица",  description = ""},
new Word { id =  59  ,callNumber = 0,numberOfLetters =7,word = "Майоран",  description = ""},
new Word { id =  60  ,callNumber = 0,numberOfLetters =7,word = "Морковь",  description = ""},
new Word { id =  61  ,callNumber = 0,numberOfLetters =7,word = "Плантан",  description = ""},
new Word { id =  62  ,callNumber = 0,numberOfLetters =7,word = "Руккола",  description = ""},
new Word { id =  63  ,callNumber = 0,numberOfLetters =7,word = "Турнепс",  description = ""},
new Word { id =  64  ,callNumber = 0,numberOfLetters =7,word = "Фенхель",  description = ""},
new Word { id =  65  ,callNumber = 0,numberOfLetters =7,word = "Цуккини",  description = ""},
new Word { id =  66  ,callNumber = 0,numberOfLetters =7,word = "Пак-чой",  description = ""},
new Word { id =  67  ,callNumber = 0,numberOfLetters =8,word = "Арракача",  description = ""},
new Word { id =  68  ,callNumber = 0,numberOfLetters =8,word = "Баклажан",  description = ""},
new Word { id =  69  ,callNumber = 0,numberOfLetters =8,word = "Брокколи",  description = ""},
new Word { id =  70  ,callNumber = 0,numberOfLetters =8,word = "Габлиция",  description = ""},
new Word { id =  71  ,callNumber = 0,numberOfLetters =8,word = "Колоцинт",  description = ""},
new Word { id =  72  ,callNumber = 0,numberOfLetters =8,word = "Кольраби",  description = ""},
new Word { id =  73  ,callNumber = 0,numberOfLetters =8,word = "Корнишон",  description = ""},
new Word { id =  74  ,callNumber = 0,numberOfLetters =8,word = "Кукуруза",  description = ""},
new Word { id =  75  ,callNumber = 0,numberOfLetters =8,word = "Мелотрия",  description = ""},
new Word { id =  76  ,callNumber = 0,numberOfLetters =8,word = "Патиссон",  description = ""},
new Word { id =  77  ,callNumber = 0,numberOfLetters =8,word = "Петрушка",  description = ""},
new Word { id =  78  ,callNumber = 0,numberOfLetters =8,word = "Радиккьо",  description = ""},
new Word { id =  79  ,callNumber = 0,numberOfLetters =8,word = "Эстрагон",  description = ""},
new Word { id =  80  ,callNumber = 0,numberOfLetters =8,word = "Абельмош",  description = ""},
new Word { id =  81  ,callNumber = 0,numberOfLetters =9,word = "Картофель",  description = ""},
new Word { id =  82  ,callNumber = 0,numberOfLetters =9,word = "Лагенария",  description = ""},
new Word { id =  83  ,callNumber = 0,numberOfLetters =9,word = "Момордика",  description = ""},
new Word { id =  84  ,callNumber = 0,numberOfLetters =9,word = "Настурция",  description = ""},
new Word { id =  85  ,callNumber = 0,numberOfLetters =9,word = "Пастернак",  description = ""},
new Word { id =  86  ,callNumber = 0,numberOfLetters =9,word = "Сельдерей",  description = ""},
new Word { id =  87  ,callNumber = 0,numberOfLetters =9,word = "Трихозант",  description = ""},
new Word { id =  88  ,callNumber = 0,numberOfLetters =10  ,word = "Романеско",  description = ""},
new Word { id =  89  ,callNumber = 0,numberOfLetters =10  ,word = "Топинамбур",  description = ""},
new Word { id =  90  ,callNumber = 0,numberOfLetters =10  ,word = "Циклантера",  description = ""},
new Word { id =  91  ,callNumber = 0,numberOfLetters =11  ,word = "Колокольчик",  description = ""},
new Word { id =  92  ,callNumber = 0,numberOfLetters =12  ,word = "Белокопытник",  description = ""},
new Word { id =  93  ,callNumber = 0,numberOfLetters =13  ,word = "Козлобородник",  description = ""}

        };

    }
}
